language: python
install: pip install tox coveralls
matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=pylint
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
script: tox
after_success: coveralls
