language: python
install: pip install tox
script: tox

jobs:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
      install: pip install tox coveralls
      after_success: coveralls
    - python: 2.7
      env: TOXENV=py27
      install: pip install tox coveralls
      after_success: coveralls
    - stage: deploy
      python: 3.6
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: fetzerch
        password:
          secure: eAgvL0+dyMoUQJlQapWCbM9JyXv0oCounQngzmdG39qJ3zXd5BxyN4UeeJKfFQzs9SaVKuU7blGPRuIpWo32xgvtiw3jZCC+1RH/oOKUINprQzLqYnOF+LZIU6+NMTdfrI7kOO2dz3vfN60qV5HdMgqFnjiu9O89iTKu5BotJFk2IGDiFqMBh2PVeWQ8d1wgQcP3GHKrODcLJzmCwMB5Mt8guUvdJxOobNc91Xul0llfmFQg3TaGR2ExMqsxOyZBcrbz6eR5tmMSm78gUN/zhICfLv8gfWAyWreOKeJUGb8KtdN6dpx05p0RtCiI6OmpiTC34FaPZWdH102aoFu+FtqhuQ7lviFvj/ED3lCamgeUJD8zmdZygrjcQQLUk5LUuUWyJ2iZUTK4ux6Ca+X/qkMAvMnxqV4nN2VZG1y8pCh/tTYDWVSo1inCrBSD43bd2eYKFvvemlVfgsd6RyYLX4inkImuWpkNu/e54LZjKxeOHl/ELk1uKRejPJmnRlxqvNEqyHlW+jvlNY6LAppEAI2pVNzZYhHaYpYriYijOtEGwcnOnXswdOwR+3B3e8E9HcWVYqXEV+XlQgOAEHF0oJKuslJiySizLdIhRXHUaqlYL9OCOG70HCjFraAMqp8lRQikjrYls5e5qtJE0nO+xwstMIUh73VMCKdJQeLmISs=
        on:
          tags: true
